import nodemailer from 'nodemailer';

export interface LeadEmailData {
  source: 'contact-page' | 'assistant-widget';
  name: string;
  organization?: string;
  phone: string;
  email: string;
  requirement?: string;
  message?: string;
}

export async function sendLeadEmail(data: LeadEmailData) {
  const recipients = ['info@cryoscientific.com'];

  // Construct HTML content
  const htmlContent = `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
      <h2 style="color: #0B3D91; border-bottom: 2px solid #1677FF; padding-bottom: 10px;">New Lead Received (${data.source === 'contact-page' ? 'Contact Form' : 'Assistant Widget'})</h2>
      
      <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
        <tr>
          <td style="padding: 8px 0; font-weight: bold; width: 150px; color: #4a5568;">Name:</td>
          <td style="padding: 8px 0; color: #2d3748;">${data.name}</td>
        </tr>
        ${data.organization ? `
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Organization:</td>
          <td style="padding: 8px 0; color: #2d3748;">${data.organization}</td>
        </tr>
        ` : ''}
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Email:</td>
          <td style="padding: 8px 0; color: #2d3748;"><a href="mailto:${data.email}">${data.email}</a></td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Phone:</td>
          <td style="padding: 8px 0; color: #2d3748;">${data.phone}</td>
        </tr>
        ${data.requirement ? `
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Requirement:</td>
          <td style="padding: 8px 0; color: #2d3748;">${data.requirement}</td>
        </tr>
        ` : ''}
        ${data.message ? `
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #4a5568; vertical-align: top;">Message:</td>
          <td style="padding: 8px 0; color: #2d3748; white-space: pre-wrap;">${data.message}</td>
        </tr>
        ` : ''}
      </table>
      
      <div style="margin-top: 30px; font-size: 11px; color: #a0aec0; border-top: 1px solid #e2e8f0; padding-top: 15px; text-align: center;">
        This email was automatically generated by CRYO SCIENTIFIC SYSTEMS Website.
      </div>
    </div>
  `;

  // Check if SMTP is configured in environment
  const smtpHost = process.env.SMTP_HOST;
  const smtpPort = process.env.SMTP_PORT;
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;

  if (smtpHost && smtpUser && smtpPass) {
    try {
      const transporter = nodemailer.createTransport({
        host: smtpHost,
        port: parseInt(smtpPort || '587'),
        secure: smtpPort === '465',
        auth: {
          user: smtpUser,
          pass: smtpPass,
        },
      });

      await transporter.sendMail({
        from: `"Cryo Lead System" <${smtpUser}>`,
        to: recipients.join(', '),
        subject: `[LEAD] ${data.name} - ${data.organization || 'Individual Inquiry'}`,
        html: htmlContent,
      });

      console.log('Lead notification email sent successfully.');
      return { success: true, method: 'smtp' };
    } catch (error) {
      console.error('SMTP Email sending failed, logging fallback:', error);
    }
  }

  // Fallback logger if credentials aren't set
  console.log('====== [LEAD EMAIL FALLBACK LOG] ======');
  console.log(`To: ${recipients.join(', ')}`);
  console.log(`Subject: [LEAD] ${data.name} - ${data.organization || 'Individual Inquiry'}`);
  console.log('HTML Body summary:');
  console.log(htmlContent.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim());
  console.log('========================================');

  return { success: true, method: 'fallback-log' };
}

export interface SupportEmailData {
  name: string;
  phone: string;
  email: string;
  purchaseDate: string;
  productName: string;
  query: string;
}

export async function sendSupportEmail(data: SupportEmailData) {
  const recipients = ['info@cryoscientific.com'];

  const htmlContent = `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
      <h2 style="color: #0B3D91; border-bottom: 2px solid #1677FF; padding-bottom: 10px;">New Support / Complaint Ticket</h2>
      
      <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
        <tr>
          <td style="padding: 8px 0; font-weight: bold; width: 180px; color: #4a5568;">Customer Name:</td>
          <td style="padding: 8px 0; color: #2d3748;">${data.name}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Email ID:</td>
          <td style="padding: 8px 0; color: #2d3748;"><a href="mailto:${data.email}">${data.email}</a></td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Phone Number:</td>
          <td style="padding: 8px 0; color: #2d3748;">${data.phone}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Product Name:</td>
          <td style="padding: 8px 0; color: #2d3748;">${data.productName}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Purchase Date:</td>
          <td style="padding: 8px 0; color: #2d3748;">${data.purchaseDate}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #4a5568; vertical-align: top;">Complaint / Query:</td>
          <td style="padding: 8px 0; color: #2d3748; white-space: pre-wrap;">${data.query}</td>
        </tr>
      </table>
      
      <div style="margin-top: 30px; font-size: 11px; color: #a0aec0; border-top: 1px solid #e2e8f0; padding-top: 15px; text-align: center;">
        This support email was automatically generated by CRYO SCIENTIFIC SYSTEMS Website.
      </div>
    </div>
  `;

  const smtpHost = process.env.SMTP_HOST;
  const smtpPort = process.env.SMTP_PORT;
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;

  if (smtpHost && smtpUser && smtpPass) {
    try {
      const transporter = nodemailer.createTransport({
        host: smtpHost,
        port: parseInt(smtpPort || '587'),
        secure: smtpPort === '465',
        auth: {
          user: smtpUser,
          pass: smtpPass,
        },
      });

      await transporter.sendMail({
        from: `"Cryo Support System" <${smtpUser}>`,
        to: recipients.join(', '),
        subject: `[SUPPORT/TICKET] ${data.productName} - ${data.name}`,
        html: htmlContent,
      });

      console.log('Support ticket email sent successfully.');
      return { success: true, method: 'smtp' };
    } catch (error) {
      console.error('SMTP Support Email sending failed, logging fallback:', error);
    }
  }

  console.log('====== [SUPPORT EMAIL FALLBACK LOG] ======');
  console.log(`To: ${recipients.join(', ')}`);
  console.log(`Subject: [SUPPORT/TICKET] ${data.productName} - ${data.name}`);
  console.log('HTML Body summary:');
  console.log(htmlContent.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim());
  console.log('==========================================');

  return { success: true, method: 'fallback-log' };
}
